### ISSUE TITLE
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee

### ISSUE THREAD

**Issue by Veenoxq** [Team-Resourceful/ResourcefulBees#165]
I'm a new modded Minecraft player, ı tried to download this mod but my game crashes everytime.,

**To Reproduce**

**Expected behavior**

**Screenshots or Crash Logs**
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
-- MOD resourcefulbees --
Details:
	Mod File: resourcefulbees-1.16.5-0.5.10b.jar
	Failure message: Resourceful Bees (resourcefulbees) has failed to load correctly
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee
	Mod Version: 1.16.5-0.5.10b
	Mod Issue URL: https://github.com/Resourceful-Bees/ResourcefulBees/issues/new/choose
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:114) ~[forge:?] {re:classloading}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.registerBee(RegistryHandler.java:151) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.lambda$registerDynamicBees$1(RegistryHandler.java:81) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.Collections$UnmodifiableMap.forEach(Unknown Source) ~[?:1.8.0_281] {}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.registerDynamicBees(RegistryHandler.java:74) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.ResourcefulBees.<init>(ResourcefulBees.java:66) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_281] {}

**please complete the following information:**
 - Forge Version 36.0.42
 - Mod Version 1.16.5-0.5.10b

**Additional context**

**Comment by Epic428** [comment]
See #151
