### ISSUE TITLE
[1.16.5] Forge 1.16.5-36.0.48 unable to start.

### ISSUE THREAD

**Issue by Edznux** [Team-Resourceful/ResourcefulBees#181]
**Describe the bug**

Resourceful bee is unable to run on forge 1.16.5-36.0.48, with `resourcefulbees-1.16.5-0.5.10b`. The server doesn't start and crashes with the attached crashlog [pastebin](https://pastebin.com/dVB29DyJ)

**To Reproduce**
Download forge `forge-1.16.5-36.0.48`, download `resourcefulbees-1.16.5-0.5.10b`, install the mod in the mods folder and start the server.

**Expected behavior**
Resourceful bee is able to start on 1.16.5 as indicated in the filename `resourcefulbees-1.16.5-0.5.10b`

**Screenshots or Crash Logs**
 [pastebin](https://pastebin.com/dVB29DyJ)

Snippet of the potentially relevant error:
```
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [resourcefulbees.mixins.json:MixinBeeEntity$MixinEnterBeehiveGoal] from phase [DEFAULT] in config [resourcefulbees.mixins.json] FAILED during APPLY
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	... 34 more
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field beeEntity was not located in the target class net.minecraft.entity.passive.BeeEntity$EnterBeehiveGoal. Using refmap resourcefulbees.refmap.json
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:616)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:292)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[01:13:24] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	... 34 more
``` 

**please complete the following information:**
 - Forge Version forge-1.16.5-36.0.48
 - Mod Version resourcefulbees-1.16.5-0.5.10b (but also tried 9_3b)

**Additional context**
Any fresh install should fail (I just tried without any other mods)
It looks like it's working fine on 1.16.4.

**Comment by Epic428** [comment]
I have the dev build of the next version working on 36.0.46. Seems after that forge changed mappings to mojmap and changed gradle stuff. So it *should* still work but I will update the dev build and test.

**Comment by Epic428** [comment]
There isn’t anything in the changelogs about mixin changes so I’m guessing it’s some kind of conflict in mappings. I’ll know more when I update forge in dev

**Comment by LlubNek** [comment]
got the same thing.  Error screen also crashed though, so the crash report might not be very useful.

resourcefulbees-1.16.5-0.5.10b
minecraft 1.16.5
forge 36.0.48

[crash-2021-03-09_21.06.56-client.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/6112654/crash-2021-03-09_21.06.56-client.txt)
[latest.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/6112655/latest.log)

This was working with the previous forge version, but I've also updated other mods since then, so no guarantees it's forge's fault and not some other mixin.

**Comment by Epic428** [comment]
The logs you posted is that the full logs? I know the mod works on 36.0.46 Bc we have a test server running with it right now for final testing of the next mod release

edit: missed you posted new ones lol

**Comment by Epic428** [comment]
Try it on forge 36.0.46 and see if you still have issues. Bc forge switched mappings in latest build I think that’s thenissue

**Comment by Epic428** [comment]
I was able to replicate the issue on the latest forge. I have have to finish some code and then I can test changes that should hopefully resolve the issue

**Comment by Epic428** [comment]
I spent about 14 hours today fighting with mappings and new forge gradle crap but it appears the mod is now working on version 36.0.54. It likely won't ever work on 48 due to class name issues in forge.

**Comment by LlubNek** [comment]
yeah, I kinda gave up on .48 myself...
