### ISSUE TITLE
Crash when multiblock centrifuge is full

### ISSUE THREAD

**Issue by aburone** [Team-Resourceful/ResourcefulBees#48]
Crash when multiblock centrifuge is full

I'm feeding cob block into a chest. A Mekanism's logistical transporter is spliting them onto two multiblock centrifuges (they're side by side)
I believe the error arises when the centrifuge output buffer gets full, but can't confirm it because the crash happens too fast. The error refers to the slot 22
Maybe It doesn't like the hopper chain...

**Expected behavior**
It should stop processing it the output buffer is temporarily full

**please complete the following information:**
 - Forge Version 32.0.108
 - Mod Version resourcefulbees-1.16.1-0.3.8a

[crash-2020-10-09_02.47.16-server.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/5352781/crash-2020-10-09_02.47.16-server.txt)
![2020-10-09_02 53 44](https://user-images.githubusercontent.com/1175830/95548135-d40bdd80-09da-11eb-85f5-374cd35d61dc.png)

**Comment by Epic428** [comment]
We have a fix for this in 1.16.3. I can backport the critical fixes to 1.16.1. But at this point there isn’t really a good reason to support 1.16.1 and everyone should simply update to the newer version. Most if not all 16.1 mods are on 16.3 at this point.

**Comment by jbreckel** [comment]
Can confirm, this still happens in 1.16.3-0.5.3b

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/19/20 10:04 AM
Description: Ticking block entity

java.lang.RuntimeException: Slot 22 not in valid range - [0,22)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:221) ~[?:?] {re:classloading}
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[?:?] {re:classloading}
	at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.centrifuge.CentrifugeControllerTileEntity.lambda$depositItemStacks$2(CentrifugeControllerTileEntity.java:205) ~[?:1.16.3-0.5.3b] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_171] {re:computing_frames}
	at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.centrifuge.CentrifugeControllerTileEntity.depositItemStacks(CentrifugeControllerTileEntity.java:202) ~[?:1.16.3-0.5.3b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.centrifuge.CentrifugeControllerTileEntity.processItem(CentrifugeControllerTileEntity.java:176) ~[?:1.16.3-0.5.3b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.centrifuge.CentrifugeControllerTileEntity.func_73660_a(CentrifugeControllerTileEntity.java:120) ~[?:1.16.3-0.5.3b] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] {}
```

[full crash-log](https://github.com/Resourceful-Bees/ResourcefulBees/files/5400127/crash-2020-10-19_10.04.36-server.txt)

**Comment by Epic428** [comment]
hmmm OK I'll take a look at it and figure out why it is still an issue thank you for reporting it

**Comment by ThatGravyBoat** [comment]
Fixed in dev.
