### ISSUE TITLE
1.16.3 random crash with multiblock apiary

### ISSUE THREAD

**Issue by aprilthepink** [Team-Resourceful/ResourcefulBees#55]
**Describe the bug**
If you create an multiblock apiary and let it run (I had in a chunkloaded area but I was in it) with bees, it crashes after some time.

**To Reproduce**
1. Start multiplayer server
2. Make multiblock apiary and fill it with bees.
3. Wait some time and have fun.
4. Multiplayer server crashes

**Expected behavior**
It shouldn't crash

Error
```
net.minecraft.crash.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262] {}
Caused by: java.lang.NullPointerException
        at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.apiary.ApiaryStorageTileEntity.deliverHoneycomb(ApiaryStorageTileEntity.java:199) ~[?:1.16.3-0.5.3b] {re:classloading}
        at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.apiary.ApiaryTileEntity.releaseBee(ApiaryTileEntity.java:192) ~[?:1.16.3-0.5.3b] {re:mixin,re:classloading}
        at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.apiary.ApiaryTileEntity.tickBees(ApiaryTileEntity.java:317) ~[?:1.16.3-0.5.3b] {re:mixin,re:classloading}
        at com.resourcefulbees.resourcefulbees.tileentity.multiblocks.apiary.ApiaryTileEntity.func_73660_a(ApiaryTileEntity.java:289) ~[?:1.16.3-0.5.3b] {re:mixin,re:classloading}
        at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
```

 - Forge Version [e.g. '1.16.3 - 34.1.18']
 - Mod Version [e.g. '0.5.3b']

**Comment by Epic428** [comment]
fixed in dev. it's because a vanilla bee went into the apiary. will be releasing the update with the fix later today. I missed a check on the vanilla bee when i added in custom Apiary amounts to bee data

**Comment by aprilthepink** [comment]
thx
