### ISSUE TITLE
Problem with creating custom bee

### ISSUE THREAD

**Issue by eternalbluepetya** [Team-Resourceful/ResourcefulBees#78]
**Describe the bug**
I'm currently creating custom bees, specifically dye and color themed ones, and for some reason when I start up the game, it says 'Resourceful Bees (resourcefulbees) has failed to load correctly, com.google.gson.JsonSyntaxException:'
The weirdest part is that it only happens with certain bees. Specifically the ones that have 2 centrifuge outputs and can be created by breeding two bees. I tried copy and pasting the new template and sticking to it as much as possible, and this error still occurs.

**Expected behavior**
I expected the game to start up normally.

**Screenshots or Crash Logs**
What I see when I start up the game:
![image](https://user-images.githubusercontent.com/75097370/100392284-e671c300-2fea-11eb-9d27-a005fc8f65d3.png)
One of the bees that crashes it:
{ 
    "flower":"ALL",
    "maxTimeInHive":2400,
    "sizeModifier":1.0,
    "hasHoneycomb":true,
    "customCombDrop": "",
    "customBombBlockDrop": "",
    "apiaryOutputAmounts" : [1,2,3,4],
    "ColorData": {
        "primaryColor":"#C9ECF9",
        "secondaryColor":"#57CDEE",
        "honeycombColor":"#358A9F",
        "isBeeColored": true,
        "isRainbowBee": false,
        "isGlowing" : false,
        "glowColor" : "#55ff55",
        "isEnchanted" : false,
        "glowingPulse" : 2
    },
    "CombatData": {  
        "isPassive": false,  
        "removeStingerOnAttack": true,
        "inflictsPoison": true,
        "attackDamage": 1
    },
    "MutationData": {
        "hasMutation":false,
        "mutationInput" : "minecraft:stone",
        "mutationOutput":"minecraft:water",
        "mutationCount":10,
        "mutationType":"BLOCK_TO_FLUID"
    },
    "CentrifugeData": {
        "hasCentrifugeOutput": true,
        "mainOutput":"minecraft:cyan_dye",
        "secondaryOutput":"minecraft:blue_dye",
        "mainOutputCount":1,
        "secondaryOutputCount":1,
        "bottleOutputCount":2,
    },
    "SpawnData": {
        "canSpawnInWorld":false,
        "spawnWeight": 8,
        "biomeWhitelist":"tag:ocean",
        "biomeBlacklist":"tag:overworld",
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "lightLevel": "ANY"
    },
    "BreedData": {
        "isBreedable": true,
        "breedWeight": 30,
        "parent1": "Cyan",
        "parent2": "Blue",
        "feedItem": "all",
        "feedAmount": 1,
        "childGrowthDelay": -24000,
        "breedDelay": 6000
    },
    "TraitData": {
        "hasTraits": false
    }
}
The crash log:
---- Minecraft Crash Report ----
// Don't do that.

Time: 11/26/20 1:18 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5106/811249375.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4882/859653366.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.33.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$445/668301868.call(Unknown Source) [forge-1.16.3-34.1.33.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?] {}
-- MOD resourcefulbees --
Details:
	Caused by 0: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 40 column 6 path $.CentrifugeData.bottleOutputCount
		at com.google.gson.Gson.fromJson(Gson.java:902) ~[gson-2.8.0.jar:?] {}
		at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
		at com.resourcefulbees.resourcefulbees.init.BeeSetup.parseBee(BeeSetup.java:65) ~[?:1.16.3-0.5.5b] {re:classloading}
		at com.resourcefulbees.resourcefulbees.init.BeeSetup.parseBee(BeeSetup.java:50) ~[?:1.16.3-0.5.5b] {re:classloading}
		at com.resourcefulbees.resourcefulbees.init.BeeSetup.addBee(BeeSetup.java:87) ~[?:1.16.3-0.5.5b] {re:classloading}
		at com.resourcefulbees.resourcefulbees.init.BeeSetup$$Lambda$3454/2026512595.accept(Unknown Source) ~[?:?] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
		at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
		at com.resourcefulbees.resourcefulbees.init.BeeSetup.addBees(BeeSetup.java:78) ~[?:1.16.3-0.5.5b] {re:classloading}
		at com.resourcefulbees.resourcefulbees.init.BeeSetup.setupBees(BeeSetup.java:41) ~[?:1.16.3-0.5.5b] {re:classloading}
		at com.resourcefulbees.resourcefulbees.ResourcefulBees.<init>(ResourcefulBees.java:95) ~[?:1.16.3-0.5.5b] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:34.1] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3048/1612625071.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3104/1226803249.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: resourcefulbees-1.16.3-0.5.5b.jar
	Failure message: Resourceful Bees (resourcefulbees) has failed to load correctly
		com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 40 column 6 path $.CentrifugeData.bottleOutputCount
	Mod Version: 1.16.3-0.5.5b
	Mod Issue URL: https://github.com/Resourceful-Bees/ResourcefulBees/issues/new/choose
	Exception message: com.google.gson.stream.MalformedJsonException: Expected name at line 40 column 6 path $.CentrifugeData.bottleOutputCount
Stacktrace:
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
	at com.resourcefulbees.resourcefulbees.init.BeeSetup.parseBee(BeeSetup.java:65) ~[?:1.16.3-0.5.5b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.init.BeeSetup.parseBee(BeeSetup.java:50) ~[?:1.16.3-0.5.5b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.init.BeeSetup.addBee(BeeSetup.java:87) ~[?:1.16.3-0.5.5b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.init.BeeSetup$$Lambda$3454/2026512595.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at com.resourcefulbees.resourcefulbees.init.BeeSetup.addBees(BeeSetup.java:78) ~[?:1.16.3-0.5.5b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.init.BeeSetup.setupBees(BeeSetup.java:41) ~[?:1.16.3-0.5.5b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.ResourcefulBees.<init>(ResourcefulBees.java:95) ~[?:1.16.3-0.5.5b] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3048/1612625071.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3104/1226803249.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 736672752 bytes (702 MB) / 2684354560 bytes (2560 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.5+84+master.3310fe0
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.33.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.33.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.33.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.33.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.33.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.33
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.33-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |CREATE_REG|NOSIGNATURE
		resourcefulbees-1.16.3-0.5.5b.jar                 |Resourceful Bees              |resourcefulbees               |1.16.3-0.5.5b       |ERROR     |NOSIGNATURE
		eggtab-1.2.5+1.16-forge.jar                       |Egg Tab                       |eggtab                        |1.2.5+1.16-forge    |CREATE_REG|NOSIGNATURE
		TrashSlot_1.16.3-12.2.0.jar                       |TrashSlot                     |trashslot                     |12.2.0              |CREATE_REG|NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |CREATE_REG|NOSIGNATURE
		morevanillalib-1.16.2-1.2.14.jar                  |MoreVanillaLib                |morevanillalib                |1.2.14              |CREATE_REG|NOSIGNATURE
		Wyrmroost-1.16.3-1.2.5.jar                        |Wyrmroost                     |wyrmroost                     |1.2.5               |CREATE_REG|NOSIGNATURE
		connectiblechains-1.0.jar                         |Connectible Chains            |connectiblechains             |1.0                 |CREATE_REG|NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |CREATE_REG|NOSIGNATURE
		jei-1.16.3-7.6.0.49.jar                           |Just Enough Items             |jei                           |7.5.0.43            |CREATE_REG|NOSIGNATURE
		villagespawnpoint_1.16.3_1.3.jar                  |Village Spawn Point           |villagespawnpoint             |1.3                 |CREATE_REG|NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.0.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |CREATE_REG|NOSIGNATURE
		Mantle-1.16.3-1.6.40.jar                          |Mantle                        |mantle                        |1.6.40              |CREATE_REG|NOSIGNATURE
		Xaeros_Minimap_20.26.0_Forge_1.16.3.jar           |Xaero's Minimap               |xaerominimap                  |20.26.0             |CREATE_REG|NOSIGNATURE
		Waystones_1.16.3-7.3.0.jar                        |Waystones                     |waystones                     |7.3.0               |CREATE_REG|NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.0.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|NOSIGNATURE
		collective-1.16.3-1.53.jar                        |Collective                    |collective                    |1.53                |CREATE_REG|NOSIGNATURE
		horse_colors-1.16.3-1.4.2.jar                     |Realistic Horse Genetics      |horse_colors                  |1.16.3-1.4.2        |CREATE_REG|NOSIGNATURE
		comforts-forge-1.16.3-4.0.0.1.jar                 |Comforts                      |comforts                      |1.16.3-4.0.0.1      |CREATE_REG|NOSIGNATURE
		citadel-1.4.1.jar                                 |Citadel                       |citadel                       |1.4.1               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-46.jar                             |AutoRegLib                    |autoreglib                    |1.6-46              |CREATE_REG|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |CREATE_REG|NOSIGNATURE
		earthmobsmod-1.16.3-0.1.2-Beta.jar                |Earth Mobs Mod                |earthmobsmod                  |1.16.3-0.1.2-Beta   |CREATE_REG|NOSIGNATURE
		good-nights-sleep-1.16.3-1.2.8.jar                |Good Night's Sleep            |good_nights_sleep             |1.2.8               |CREATE_REG|NOSIGNATURE
		Bookshelf-1.16.3-8.7.20.jar                       |Bookshelf                     |bookshelf                     |8.7.20              |CREATE_REG|NOSIGNATURE
		EnchantmentDescriptions-1.16.3-5.0.1.jar          |EnchantmentDescriptions       |enchdesc                      |5.0.1               |CREATE_REG|NOSIGNATURE
		HerdMentality-1.16.3-4.0.1.jar                    |HerdMentality                 |herdmentality                 |4.0.1               |CREATE_REG|NOSIGNATURE
		worldedit-forge-mc1.16.3-7.2.0-rc2-dist.jar       |WorldEdit                     |worldedit                     |7.2.0-rc2+a615e01   |CREATE_REG|NOSIGNATURE
		u_team_core-1.16.3-3.1.10.183.jar                 |U Team Core                   |uteamcore                     |3.1.10.183          |CREATE_REG|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		LightingWand-1.16.3-1.7.1.jar                     |Lighting Wand                 |lightingwand                  |1.7.1               |CREATE_REG|NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |CREATE_REG|NOSIGNATURE
		BackTools-1.16.3-10.0.0.jar                       |Back Tools                    |backtools                     |10.0.0              |CREATE_REG|NOSIGNATURE
		productivebees-1.16.3-0.4.1.4.jar                 |Productive Bees               |productivebees                |1.16.3-0.4.1.4      |CREATE_REG|NOSIGNATURE
		iChunUtil-1.16.3-10.0.0.jar                       |iChunUtil                     |ichunutil                     |10.0.0              |CREATE_REG|NOSIGNATURE
		the_bumblezone-1.16.4-2.2.4.jar                   |The Bumblezone                |the_bumblezone                |1.16.4-2.2.4        |CREATE_REG|NOSIGNATURE
		forge-1.16.3-34.1.33-universal.jar                |Forge                         |forge                         |34.1.33             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-271.jar                                |Quark                         |quark                         |r2.4-271            |CREATE_REG|NOSIGNATURE
		blame-1.16.4-1.5.0.jar                            |Blame!                        |blame                         |1.16.4-1.5.0        |CREATE_REG|NOSIGNATURE
		theparakeetmod-Forge-1.16.3-1.0.6.jar             |The Parakeet Mod              |parakeetmod                   |1.16.3-1.0.6        |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 882b6dcf-d208-44aa-ba90-fbc539c63320
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 16
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6446
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 4

**please complete the following information:**
 - Forge Version: 1.16.3-forge-34.1.33
 - Mod Version: resourcefulbees-1.16.3-0.4.1.4

**Comment by Epic428** [comment]
Give me an hour to get to work and I’ll look it over and let you know how to fix it

**Comment by eternalbluepetya** [comment]
> 
> 
> Give me an hour to get to work and I’ll look it over and let you know how to fix it

Thank you so much!

**Comment by jtmnf** [comment]
Hi @eternalbluepetya . Just want to say that you have an extra comma in your Json, and that's probably why your are getting the error "JsonSyntaxException". In the "CentrifugeData"   object, your last item should not have comma, because it is the end of the object.

You can use https://jsonlint.com/ in order to test if your Json file is valid or not.

**Comment by eternalbluepetya** [comment]
@jtmnf That website helped alot, thanks!

**Comment by Epic428** [comment]
I just wanted to add a side note. You don’t *have* to use the full template either. The wiki breaks down each section and covers what is required and when and why. So most options can be left out if not needed or only default values are needed.
