### ISSUE TITLE
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee

### ISSUE THREAD

**Issue by Hurricane144** [Team-Resourceful/ResourcefulBees#97]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
Crash

**To Reproduce**

**Expected behavior**

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version 35.1.4
 - Mod Version 0.5.6b

**Additional context**
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: 
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:classloading,re:mixin}
-- MOD resourcefulbees --
Details:
	Mod File: ResourcefulBees1.16.3-1.16.3-0.5.6b.jar
	Failure message: Resourceful Bees (resourcefulbees) has failed to load correctly
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee
	Mod Version: 1.16.3-0.5.6b
	Mod Issue URL: https://github.com/Resourceful-Bees/ResourcefulBees/issues/new/choose
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:114) ~[forge:?] {re:classloading}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.registerBee(RegistryHandler.java:140) ~[resourcefulbees:1.16.3-0.5.6b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.lambda$registerDynamicBees$1(RegistryHandler.java:77) ~[resourcefulbees:1.16.3-0.5.6b] {re:classloading}
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.Collections$UnmodifiableMap.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.registerDynamicBees(RegistryHandler.java:70) ~[resourcefulbees:1.16.3-0.5.6b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.ResourcefulBees.<init>(ResourcefulBees.java:74) ~[resourcefulbees:1.16.3-0.5.6b] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}

-- MOD envirocore --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: com/valkyrieofnight/vlib/core/obj/tileentity/base/IOnActivated
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271] {}
		at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.6.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271] {}
		at com.valkyrieofnight.envirocore.m_comp.m_io.CIOModule.registerAssets(CIOModule.java:80) ~[envirocore:1.16.4-3.0.5.2] {re:classloading}
		at com.valkyrieofnight.vlib.module.base.VLModule._2registerAssets(VLModule.java:62) ~[valkyrielib:?] {re:classloading}
		at com.valkyrieofnight.vlib.module.base.VLModule._2registerAssets(VLModule.java:66) ~[valkyrielib:?] {re:classloading}
		at com.valkyrieofnight.vlib.module.base.VLModule._2registerAssets(VLModule.java:66) ~[valkyrielib:?] {re:classloading}
		at com.valkyrieofnight.vlib.module.proxy.ProxyCommon.registerAssets(ProxyCommon.java:28) ~[valkyrielib:?] {re:classloading}
		at com.valkyrieofnight.vlib.module.base.VLMod.setup2(VLMod.java:117) ~[valkyrielib:?] {re:classloading}
		at com.valkyrieofnight.vlib.module.base.VLMod.<init>(VLMod.java:90) ~[valkyrielib:?] {re:classloading}
		at com.valkyrieofnight.vlib.modloader.VLForgeMod.<init>(VLForgeMod.java:21) ~[valkyrielib:?] {re:classloading}
		at com.valkyrieofnight.envirocore.EnviroCore.<init>(EnviroCore.java:39) ~[envirocore:1.16.4-3.0.5.2] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:35.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}

**Comment by ThatGravyBoat** [comment]
use a valid character in your bees json ı is not a valid character

**Comment by ThatGravyBoat** [comment]
bee json name*

**Comment by Hurricane144** [comment]
This is not my mod and I dont know how to fix it I already know that ı is not a valid character.

**Comment by Hurricane144** [comment]
and when I tried to check to folder for any "ı" I could not find any

**Comment by ThatGravyBoat** [comment]
what lang is your computer in?

**Comment by Hurricane144** [comment]
Turkish

**Comment by Hurricane144** [comment]
Now I am using english and it works

**Comment by Epic428** [comment]
Fixed in #d0e4f1d39dff5b113cae2c2b1add2d8157d65706 (I think it’s this commit)
